"""
TryScope - HTML report generator
Produces a single self-contained HTML file with the map + tables.
"""
from pathlib import Path
import time

from .. import logger
from . import map as map_mod


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>TryScope - {ip}</title>
<style>
  :root {{
    --bg: #0f1117; --card: #1a1d29; --border: #2a2f3f;
    --text: #d8dee9; --muted: #8892a0; --blue: #4cc9f0;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; padding: 40px 20px; background: var(--bg);
    color: var(--text);
    font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
    line-height: 1.5;
  }}
  .container {{ max-width: 1100px; margin: 0 auto; }}
  header {{
    padding-bottom: 20px; border-bottom: 1px solid var(--border);
    margin-bottom: 30px;
  }}
  h1 {{ margin: 0 0 8px; font-size: 28px; color: var(--blue); }}
  h2 {{ font-size: 20px; margin: 30px 0 12px; color: var(--blue); }}
  .meta {{ color: var(--muted); font-size: 13px; }}
  .summary {{
    display: grid; grid-template-columns:
    repeat(auto-fit, minmax(150px, 1fr));
    gap: 12px; margin: 20px 0;
  }}
  .stat {{
    background: var(--card); border: 1px solid var(--border);
    border-radius: 8px; padding: 16px; text-align: center;
  }}
  .stat .num {{
    font-size: 32px; font-weight: bold; color: var(--blue);
    display: block;
  }}
  .stat .lbl {{
    color: var(--muted); font-size: 12px; text-transform: uppercase;
  }}
  table {{
    width: 100%; border-collapse: collapse; background: var(--card);
    border: 1px solid var(--border); border-radius: 8px;
    overflow: hidden; margin-bottom: 20px; font-size: 14px;
  }}
  th, td {{
    padding: 10px 12px; text-align: left;
    border-bottom: 1px solid var(--border);
  }}
  th {{
    background: #14171f; color: var(--muted); font-weight: 600;
    font-size: 12px; text-transform: uppercase;
  }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover {{ background: #1f2330; }}
  code {{
    background: #14171f; padding: 2px 6px; border-radius: 4px;
    color: var(--blue); font-size: 13px;
  }}
  footer {{
    margin-top: 40px; padding-top: 20px;
    border-top: 1px solid var(--border);
    text-align: center; color: var(--muted); font-size: 12px;
  }}
  .verdict-critical {{ color: #ff6b6b; font-weight: bold; }}
  .verdict-high     {{ color: #ffa94d; font-weight: bold; }}
  .verdict-medium   {{ color: #ffd43b; font-weight: bold; }}
  .verdict-low      {{ color: #a0e3ff; font-weight: bold; }}
  .verdict-clean    {{ color: var(--blue); font-weight: bold; }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>TryScope Report</h1>
    <div class="meta">
      Target: <code>{ip}</code> &nbsp;|&nbsp;
      Generated: {generated_at}
    </div>
  </header>

  {map_html}

  <h2>Summary</h2>
  <div class="summary">
    <div class="stat">
      <span class="num {verdict_class}">{score}</span>
      <span class="lbl">Risk Score</span>
    </div>
    <div class="stat">
      <span class="num">{level}</span>
      <span class="lbl">Level</span>
    </div>
    <div class="stat">
      <span class="num">{cluster_ips}</span>
      <span class="lbl">Cluster IPs</span>
    </div>
    <div class="stat">
      <span class="num">{cluster_domains}</span>
      <span class="lbl">Domains</span>
    </div>
    <div class="stat">
      <span class="num">{blacklists}</span>
      <span class="lbl">Blacklists</span>
    </div>
  </div>

  <h2>Geolocation</h2>
  <table>{geo_rows}</table>

  <h2>Country</h2>
  <table>{country_rows}</table>

  <h2>Network</h2>
  <table>{network_rows}</table>

  <h2>Reputation</h2>
  <table>{reputation_rows}</table>

  <h2>Pivot Results</h2>
  <table>{pivot_rows}</table>

  <h2>Verdict</h2>
  <table>{verdict_rows}</table>

  <footer>
    Generated by TryScope v1.0 &nbsp;|&nbsp;
    IP Intelligence
  </footer>
</div>
</body>
</html>
"""


def _rows(pairs):
    out = []
    for k, v in pairs:
        if v in (None, "", [], 0):
            continue
        out.append(f"<tr><td>{k}</td><td><code>{v}</code></td></tr>")
    return "".join(out)


def generate(data: dict, out_path: str = "report.html") -> str:
    ip = data.get("ip", "?")
    country = data.get("country", {}) or {}
    rdap = data.get("rdap", {}) or {}
    internetdb = data.get("internetdb", {}) or {}
    abuse = data.get("abuseipdb", {}) or {}
    vt = data.get("virustotal", {}) or {}
    gn = data.get("greynoise", {}) or {}
    bl = data.get("blacklists", {}) or {}
    fav = data.get("favicon", {}) or {}
    jarm_data = data.get("jarm", {}) or {}
    cert_data = data.get("cert", {}) or {}
    dns_hist = data.get("dns_history", {}) or {}
    bgp = data.get("bgp", {}) or {}
    cluster = data.get("cluster", {}) or {}
    verdict = data.get("verdict", {}) or {}

    lat = country.get("lat", 0)
    lon = country.get("lon", 0)
    map_html = map_mod.render(lat, lon, ip) if (lat and lon) else ""

    score = verdict.get("score", 0)
    level = verdict.get("level", "CLEAN")
    verdict_class = f"verdict-{level.lower()}"

    html = HTML_TEMPLATE.format(
        ip=ip,
        generated_at=time.strftime("%Y-%m-%d %H:%M:%S"),
        map_html=map_html,
        score=score,
        level=level,
        verdict_class=verdict_class,
        cluster_ips=cluster.get("stats", {}).get("total_ips", 0),
        cluster_domains=cluster.get("stats", {}).get("total_domains", 0),
        blacklists=f"{bl.get('total_listed', 0)}/{bl.get('total_checked', 0)}",
        geo_rows=_rows([
            ("Country", country.get("country")),
            ("Country code", country.get("country_code")),
            ("Region", country.get("region")),
            ("City", country.get("city")),
            ("Postal", country.get("postal")),
            ("Coordinates", f"{lat}, {lon}" if (lat or lon) else ""),
            ("Timezone", country.get("timezone")),
            ("Local time", country.get("local_time")),
            ("Google Maps", country.get("google_maps_url")),
        ]),
        country_rows=_rows([
            ("Capital", country.get("capital")),
            ("Population", f"{country.get('population', 0):,}"
             if country.get("population") else ""),
            ("Currency", f"{country.get('currency_code', '')} "
             f"{country.get('currency_symbol', '')}"),
            ("Calling code", country.get("calling_code")),
            ("Languages", ", ".join(country.get("languages", [])[:5])),
        ]),
        network_rows=_rows([
            ("ISP", country.get("isp")),
            ("Organization", country.get("org") or rdap.get("organization")),
            ("ASN", country.get("asn")),
            ("CIDR", bgp.get("target_prefix")),
            ("Reverse DNS", country.get("reverse_dns")),
            ("Open ports", ", ".join(str(p)
             for p in internetdb.get("ports", [])[:20])),
            ("CVEs", ", ".join(internetdb.get("vulns", [])[:5])),
        ]),
        reputation_rows=_rows([
            ("AbuseIPDB score", f"{abuse.get('score', 0)}/100"
             if abuse else ""),
            ("Abuse reports", abuse.get("total_reports")),
            ("VirusTotal", f"{vt.get('malicious', 0)}/"
             f"{vt.get('total_engines', 0)} engines" if vt else ""),
            ("Malware families", ", ".join(vt.get("malware_families", [])[:3])),
            ("GreyNoise", gn.get("classification", "")),
            ("Blacklists", f"{bl.get('total_listed', 0)}/"
             f"{bl.get('total_checked', 0)}"),
        ]),
        pivot_rows=_rows([
            ("Favicon hash", f"mmh3:{fav['hash']}"
             if fav.get("hash") is not None else ""),
            ("JARM", jarm_data.get("jarm", "")[:32]),
            ("Cert siblings", cert_data.get("total_found")),
            ("Reverse IP domains", dns_hist.get("total_domains")),
            ("BGP CIDRs", bgp.get("total_cidrs")),
        ]),
        verdict_rows=_rows([
            ("Score", f"{score}/100"),
            ("Level", level),
            ("Verdict", verdict.get("verdict", "")),
            ("Confidence", verdict.get("confidence", "")),
            ("Recommendation", verdict.get("recommendation", "")),
            ("MITRE", ", ".join(verdict.get("mitre", [])[:5])),
        ]),
    )

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    logger.ok(f"HTML report saved: {out}")
    return str(out)
